spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myjobs
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
  batch:
    initialize-schema: always